import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#06142E',
  },
  header: {
    minHeight: 172,
    backgroundColor: '#061C46',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 42,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerCopy: {
    flex: 1,
    paddingRight: 18,
  },
  brand: {
    color: '#8FD8FF',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 12,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '900',
  },
  homeButton: {
    minWidth: 54,
    height: 32,
    borderRadius: 10,
    paddingHorizontal: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeButtonText: {
    color: '#082D63',
    fontSize: 13,
    fontWeight: '900',
  },
  content: {
    flex: 1,
    marginTop: -28,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#06142E',
  },
  contentContainer: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 34,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '900',
    marginBottom: 14,
  },
  routesCard: {
    padding: 16,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    shadowColor: '#001B44',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.20,
    shadowRadius: 22,
    elevation: 6,
  },
  routesList: {
    gap: 10,
    paddingRight: 8,
    paddingBottom: 2,
  },
  routeButton: {
    minWidth: 124,
    maxWidth: 220,
    minHeight: 54,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeDot: {
    width: 13,
    height: 13,
    borderRadius: 7,
    marginRight: 10,
  },
  routeButtonText: {
    flexShrink: 1,
    color: '#082D63',
    fontSize: 15,
    fontWeight: '900',
  },
  routeButtonTextActive: {
    color: '#FFFFFF',
  },
  errorCard: {
    marginTop: 16,
    padding: 15,
    borderRadius: 14,
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
  },
  routesEmptyText: {
    color: '#D6E8FF',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 4,
  },
  errorTitle: {
    color: '#9F1239',
    fontSize: 15,
    fontWeight: '900',
  },
  errorText: {
    color: '#BE123C',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  errorAction: {
    color: '#9F1239',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 7,
  },
  mapCard: {
    marginTop: 24,
    padding: 14,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    shadowColor: '#001B44',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 7,
  },
  mapHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  mapHeaderCopy: {
    flex: 1,
    paddingRight: 12,
  },
  mapEyebrow: {
    color: '#8FD8FF',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 3,
  },
  mapTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  mapContainer: {
    height: 280,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#092453',
  },
  map: {
    flex: 1,
  },
  mapEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  mapEmptyText: {
    color: '#D6E8FF',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  mapButton: {
    position: 'absolute',
    left: 14,
    bottom: 14,
    minHeight: 46,
    paddingHorizontal: 17,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 4,
  },
  mapGlassOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 44,
    backgroundColor: 'rgba(6, 20, 46, 0.16)',
  },
  mapPin: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#073D8F',
    marginRight: 9,
  },
  mapButtonText: {
    color: '#082D63',
    fontSize: 14,
    fontWeight: '900',
  },
  dataPanel: {
    marginTop: 20,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#073D8F',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    shadowColor: '#001E49',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 7,
  },
  panelTabs: {
    minHeight: 64,
    padding: 8,
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#052F70',
  },
  panelTab: {
    flex: 1,
    minHeight: 47,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelTabActive: {
    backgroundColor: '#FFFFFF',
  },
  panelTabText: {
    color: '#A9CDF6',
    fontSize: 10,
    fontWeight: '900',
  },
  panelTabTextActive: {
    color: '#073D8F',
  },
  panelHeader: {
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  panelTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  panelRouteName: {
    color: '#8FD8FF',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
  },
  panelContent: {
    padding: 18,
    paddingTop: 14,
  },
  feedback: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackText: {
    color: '#C9E3FF',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  emptyText: {
    color: '#D8E9FC',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    paddingVertical: 25,
  },
  dataRow: {
    minHeight: 64,
    borderRadius: 13,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: 9,
  },
  dataIndex: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 11,
  },
  dataIndexText: {
    color: '#073D8F',
    fontSize: 13,
    fontWeight: '900',
  },
  dataCopy: {
    flex: 1,
  },
  dataTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  dataDescription: {
    color: '#A9CDF6',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  scheduleCard: {
    borderRadius: 13,
    padding: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: 9,
  },
  schedulePoint: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 9,
  },
  scheduleTimes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  timePill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  timeText: {
    color: '#073D8F',
    fontSize: 12,
    fontWeight: '900',
  },
  driverCard: {
    borderRadius: 15,
    padding: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.11)',
    marginBottom: 11,
  },
  avatar: {
    width: 62,
    height: 62,
    borderRadius: 16,
    backgroundColor: '#DCEBFC',
    marginBottom: 11,
  },
  driverInfo: {
    marginBottom: 12,
  },
  driverName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  driverCode: {
    color: '#A9CDF6',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  statusPill: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: '#DDF8E8',
    marginTop: 8,
  },
  statusText: {
    color: '#197A42',
    fontSize: 11,
    fontWeight: '900',
  },
  driverRating: {
    color: '#D8E9FC',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  driverActions: {
    flexDirection: 'row',
    gap: 8,
  },
  driverPrimaryButton: {
    flex: 1,
    minHeight: 43,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  driverPrimaryText: {
    color: '#073D8F',
    fontSize: 13,
    fontWeight: '900',
  },
  driverSecondaryButton: {
    flex: 1.25,
    minHeight: 43,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#8FD8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverSecondaryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
});

export default styles;
