import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#081020',
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 15, 32, 0.68)',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 82,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 22,
    elevation: 10,
  },
  headerTitleRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  headerTitle: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 21,
    fontWeight: '900',
    marginLeft: 10,
  },
  busIcon: {
    borderColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 2,
    flexDirection: 'row',
    height: 24,
    justifyContent: 'space-evenly',
    paddingTop: 4,
    position: 'relative',
    width: 30,
  },
  busWindow: {
    backgroundColor: '#FFFFFF',
    borderRadius: 1,
    height: 7,
    width: 8,
  },
  busWheelLeft: {
    backgroundColor: '#FFFFFF',
    borderRadius: 3,
    bottom: -4,
    height: 6,
    left: 4,
    position: 'absolute',
    width: 6,
  },
  busWheelRight: {
    backgroundColor: '#FFFFFF',
    borderRadius: 3,
    bottom: -4,
    height: 6,
    position: 'absolute',
    right: 4,
    width: 6,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#1E3A8A',
    borderRadius: 11,
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  logoutText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    marginLeft: 7,
  },
  logoutIcon: {
    color: '#FFFFFF',
    fontSize: 27,
    fontWeight: '500',
    lineHeight: 28,
    transform: [{ rotate: '180deg' }],
  },
  scrollContent: {
    paddingBottom: 34,
    paddingHorizontal: 16,
    paddingTop: 30,
  },
  intro: {
    marginBottom: 24,
  },
  eyebrow: {
    color: '#BFDBFE',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  pageTitle: {
    color: '#FFFFFF',
    fontSize: 31,
    fontWeight: '900',
    letterSpacing: -0.7,
    lineHeight: 37,
  },
  pageDescription: {
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 23,
    marginTop: 10,
    maxWidth: 620,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  cardShell: {
    borderRadius: 20,
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 9,
  },
  cardFull: {
    width: '100%',
  },
  cardHalf: {
    width: '48.6%',
  },
  cardTouchArea: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.11)',
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 380,
    overflow: 'hidden',
  },
  cardContent: {
    flex: 1,
    padding: 20,
  },
  cardImage: {
    alignSelf: 'center',
    height: 126,
    width: '100%',
  },
  cardIconArea: {
    alignItems: 'center',
    height: 126,
    justifyContent: 'center',
  },
  driverIcon: {
    alignItems: 'center',
    height: 100,
    justifyContent: 'flex-end',
    position: 'relative',
    width: 112,
  },
  driverHead: {
    borderColor: '#DBEAFE',
    borderRadius: 23,
    borderWidth: 7,
    height: 46,
    position: 'absolute',
    top: 3,
    width: 46,
  },
  driverBody: {
    borderColor: '#DBEAFE',
    borderBottomWidth: 0,
    borderRadius: 34,
    borderWidth: 7,
    height: 52,
    width: 72,
  },
  driverPlus: {
    color: '#DBEAFE',
    fontSize: 42,
    fontWeight: '600',
    position: 'absolute',
    right: 0,
    top: 43,
  },
  cardCopy: {
    flex: 1,
    marginTop: 12,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 27,
  },
  cardDescription: {
    color: 'rgba(255, 255, 255, 0.76)',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 21,
    marginTop: 9,
  },
  cardActions: {
    marginTop: 18,
  },
  actionButton: {
    borderRadius: 11,
    marginTop: 10,
    overflow: 'hidden',
  },
  actionGradient: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
  },
  actionIcon: {
    alignItems: 'center',
    borderColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 5,
    borderWidth: 1.5,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  actionIconText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 15,
  },
  actionText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    marginLeft: 8,
  },
});

export default styles;
